"""create_lesson_history_table

Revision ID: dd2393c23595
Revises: e05e7d116bf1
Create Date: 2026-01-28 15:52:46.076641

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dd2393c23595'
down_revision: Union[str, None] = 'e05e7d116bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('lesson_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_history_id'), 'lesson_history', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_history_user_id'), 'lesson_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_history_user_id'), table_name='lesson_history')
    op.drop_index(op.f('ix_lesson_history_id'), table_name='lesson_history')
    op.drop_table('lesson_history')
    # ### end Alembic commands ###
